version: "2.2"

services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT
    volumes:
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db:/var/lib/mysql"

  filesys:
    depends_on:
      - mysqldb
    image: filesys
    container_name: file-system
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: $MYSQLDB_DOCKER_PORT
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    volumes:
      - ./uploads:/uploads
