version: "2.2"

services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT
    volumes:
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"